### ISSUE TITLE
Review article: Deploying Torrust To Production

### ISSUE THREAD

**Issue by josecelano** [torrust/torrust-website-v1#138]
Live article: https://torrust.com/deploying-torrust-to-production

After merging this PR:

https://github.com/torrust/torrust-index/pull/480

Now you can use the env var `TORRUST_INDEX_AUTH_SECRET_KEY` to inject the option value. So you don't need to edit the config.toml file. It seems the article does not even mention that you have to generate a `secret_key`.

```toml
[auth]
email_on_signup = "Optional"
min_password_length = 6
max_password_length = 64
secret_key = "MaxVerstappenWC2021"
```
