### ISSUE TITLE
Update Tracker and Index TOML config files

### ISSUE THREAD

**Issue by josecelano** [torrust/torrust-website-v1#206]
Relates to: 

- https://github.com/torrust/torrust-index/issues/591
- https://github.com/torrust/torrust-tracker/issues/878

### Index

After merging [this Index PR](https://github.com/torrust/torrust-index/pull/631), some breaking changes will be introduced in the Index config files.

We have to update all articles containing Index config files.

#### Deprecated configuration

```toml
log_level = "info"

[website]
name = "Torrust"

[tracker]
api_url = "http://localhost:1212"
mode = "Public"
token = "MyAccessToken"
token_valid_seconds = 7257600
url = "udp://localhost:6969"

[net]
port = 3001

# Uncomment if you want to enable TSL for development
#[net.tsl]
#ssl_cert_path = "./storage/index/lib/tls/localhost.crt"
#ssl_key_path = "./storage/index/lib/tls/localhost.key"

[auth]
email_on_signup = "Optional"
max_password_length = 64
min_password_length = 6
secret_key = "MaxVerstappenWC2021"

[database]
connect_url = "sqlite://data.db?mode=rwc"

[mail]
email_verification_enabled = false
from = "example@email.com"
password = ""
port = 25
reply_to = "noreply@email.com"
server = ""
username = ""

[image_cache]
capacity = 128000000
entry_size_limit = 4000000
max_request_timeout_ms = 1000
user_quota_bytes = 64000000
user_quota_period_seconds = 3600

[api]
default_torrent_page_size = 10
max_torrent_page_size = 30

[tracker_statistics_importer]
port = 3002
torrent_info_update_interval = 3600
```

#### New configuration

```toml
[metadata]
app = "torrust-index"
purpose = "configuration"
schema_version = "2.0.0"

[logging]
threshold = "info"

[website]
name = "Torrust"

[tracker]
api_url = "http://localhost:1212/"
listed = false
private = false
token = "***"
token_valid_seconds = 7_257_600
url = "udp://localhost:6969"

[net]
bind_address = "0.0.0.0:3001"

[auth]
user_claim_token_pepper = "***"

  [auth.password_constraints]
  max_password_length = 64
  min_password_length = 6

[database]
connect_url = "sqlite://data.db?mode=rwc"

[mail]
from = "example@email.com"
reply_to = "noreply@email.com"

  [mail.smtp]
  port = 25
  server = ""

    [mail.smtp.credentials]
    password = "***"
    username = ""

[image_cache]
capacity = 128_000_000
entry_size_limit = 4_000_000
max_request_timeout_ms = 1_000
user_quota_bytes = 64_000_000
user_quota_period_seconds = 3_600

[api]
default_torrent_page_size = 10
max_torrent_page_size = 30

[registration.email]
required = false
verification_required = false

[tracker_statistics_importer]
port = 3_002
torrent_info_update_interval = 3_600

```

Env vars also changed:

```
TORRUST_INDEX_CONFIG_OVERRIDE_AUTH__SECRET_KEY -> TORRUST_INDEX_CONFIG_OVERRIDE_AUTH__USER_CLAIM_TOKEN_PEPPER
```

#### Deprecated configuration

```toml
log_level = "info"
mode = "public"
db_driver = "Sqlite3"
db_path = "./storage/tracker/lib/database/sqlite3.db"
announce_interval = 120
min_announce_interval = 120
on_reverse_proxy = false
external_ip = "0.0.0.0"
tracker_usage_statistics = true
persistent_torrent_completed_stat = false
max_peer_timeout = 900
inactive_peer_cleanup_interval = 600
remove_peerless_torrents = true

[[udp_trackers]]
enabled = false
bind_address = "0.0.0.0:6969"

[[http_trackers]]
enabled = false
bind_address = "0.0.0.0:7070"
ssl_enabled = false
ssl_cert_path = ""
ssl_key_path = ""

[http_api]
enabled = true
bind_address = "127.0.0.1:1212"
ssl_enabled = false
ssl_cert_path = ""
ssl_key_path = ""

[http_api.access_tokens]
admin = "MyAccessToken"

[health_check_api]
bind_address = "127.0.0.1:1313"
```

#### New configuration

```toml
[metadata]
app = "torrust-tracker"
purpose = "configuration"
schema_version = "2.0.0"

[logging]
threshold = "info"

[core]
inactive_peer_cleanup_interval = 600
listed = false
private = false
tracker_usage_statistics = true

  [core.announce_policy]
  interval = 120
  interval_min = 120

  [core.database]
  driver = "sqlite3"
  path = "./storage/tracker/lib/database/sqlite3.db"

  [core.net]
  external_ip = "0.0.0.0"
  on_reverse_proxy = false

  [core.tracker_policy]
  max_peer_timeout = 900
  persistent_torrent_completed_stat = false
  remove_peerless_torrents = true

[[udp_trackers]]
bind_address = "0.0.0.0:6969"

[[http_trackers]]
bind_address = "0.0.0.0:7070"

[http_api]
bind_address = "0.0.0.0:1212"

  [http_api.access_tokens]
  admin = "***"

[health_check_api]
bind_address = "127.0.0.1:1313"

```

Env vars also change:

```text
TORRUST_TRACKER_CONFIG_OVERRIDE_DB_DRIVER -> TORRUST_TRACKER_CONFIG_OVERRIDE_CORE__DATABASE__DRIVER
TORRUST_INDEX_CONFIG_OVERRIDE_AUTH__SECRET_KEY -> TORRUST_INDEX_CONFIG_OVERRIDE_AUTH__USER_CLAIM_TOKEN_PEPPER
```
